// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/znmaster911/L2-calendar/pkg/repositories.Events -o events_mock.go -n EventsMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	"time"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/znmaster911/L2-calendar/internal/models"
)

// EventsMock implements mm_repositories.Events
type EventsMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteEvent          func(userID int64, eventID int64) (err error)
	funcDeleteEventOrigin    string
	inspectFuncDeleteEvent   func(userID int64, eventID int64)
	afterDeleteEventCounter  uint64
	beforeDeleteEventCounter uint64
	DeleteEventMock          mEventsMockDeleteEvent

	funcGetEvents          func(dateStart time.Time, dateEnd time.Time, userID int) (ra1 []models.Reply, err error)
	funcGetEventsOrigin    string
	inspectFuncGetEvents   func(dateStart time.Time, dateEnd time.Time, userID int)
	afterGetEventsCounter  uint64
	beforeGetEventsCounter uint64
	GetEventsMock          mEventsMockGetEvents

	funcNewEvent          func(userId int64, event models.Event) (err error)
	funcNewEventOrigin    string
	inspectFuncNewEvent   func(userId int64, event models.Event)
	afterNewEventCounter  uint64
	beforeNewEventCounter uint64
	NewEventMock          mEventsMockNewEvent

	funcUpdateEvent          func(userID int64, eventID int64, input models.UpdateEvent) (err error)
	funcUpdateEventOrigin    string
	inspectFuncUpdateEvent   func(userID int64, eventID int64, input models.UpdateEvent)
	afterUpdateEventCounter  uint64
	beforeUpdateEventCounter uint64
	UpdateEventMock          mEventsMockUpdateEvent
}

// NewEventsMock returns a mock for mm_repositories.Events
func NewEventsMock(t minimock.Tester) *EventsMock {
	m := &EventsMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteEventMock = mEventsMockDeleteEvent{mock: m}
	m.DeleteEventMock.callArgs = []*EventsMockDeleteEventParams{}

	m.GetEventsMock = mEventsMockGetEvents{mock: m}
	m.GetEventsMock.callArgs = []*EventsMockGetEventsParams{}

	m.NewEventMock = mEventsMockNewEvent{mock: m}
	m.NewEventMock.callArgs = []*EventsMockNewEventParams{}

	m.UpdateEventMock = mEventsMockUpdateEvent{mock: m}
	m.UpdateEventMock.callArgs = []*EventsMockUpdateEventParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mEventsMockDeleteEvent struct {
	optional           bool
	mock               *EventsMock
	defaultExpectation *EventsMockDeleteEventExpectation
	expectations       []*EventsMockDeleteEventExpectation

	callArgs []*EventsMockDeleteEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// EventsMockDeleteEventExpectation specifies expectation struct of the Events.DeleteEvent
type EventsMockDeleteEventExpectation struct {
	mock               *EventsMock
	params             *EventsMockDeleteEventParams
	paramPtrs          *EventsMockDeleteEventParamPtrs
	expectationOrigins EventsMockDeleteEventExpectationOrigins
	results            *EventsMockDeleteEventResults
	returnOrigin       string
	Counter            uint64
}

// EventsMockDeleteEventParams contains parameters of the Events.DeleteEvent
type EventsMockDeleteEventParams struct {
	userID  int64
	eventID int64
}

// EventsMockDeleteEventParamPtrs contains pointers to parameters of the Events.DeleteEvent
type EventsMockDeleteEventParamPtrs struct {
	userID  *int64
	eventID *int64
}

// EventsMockDeleteEventResults contains results of the Events.DeleteEvent
type EventsMockDeleteEventResults struct {
	err error
}

// EventsMockDeleteEventOrigins contains origins of expectations of the Events.DeleteEvent
type EventsMockDeleteEventExpectationOrigins struct {
	origin        string
	originUserID  string
	originEventID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteEvent *mEventsMockDeleteEvent) Optional() *mEventsMockDeleteEvent {
	mmDeleteEvent.optional = true
	return mmDeleteEvent
}

// Expect sets up expected params for Events.DeleteEvent
func (mmDeleteEvent *mEventsMockDeleteEvent) Expect(userID int64, eventID int64) *mEventsMockDeleteEvent {
	if mmDeleteEvent.mock.funcDeleteEvent != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Set")
	}

	if mmDeleteEvent.defaultExpectation == nil {
		mmDeleteEvent.defaultExpectation = &EventsMockDeleteEventExpectation{}
	}

	if mmDeleteEvent.defaultExpectation.paramPtrs != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by ExpectParams functions")
	}

	mmDeleteEvent.defaultExpectation.params = &EventsMockDeleteEventParams{userID, eventID}
	mmDeleteEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteEvent.expectations {
		if minimock.Equal(e.params, mmDeleteEvent.defaultExpectation.params) {
			mmDeleteEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteEvent.defaultExpectation.params)
		}
	}

	return mmDeleteEvent
}

// ExpectUserIDParam1 sets up expected param userID for Events.DeleteEvent
func (mmDeleteEvent *mEventsMockDeleteEvent) ExpectUserIDParam1(userID int64) *mEventsMockDeleteEvent {
	if mmDeleteEvent.mock.funcDeleteEvent != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Set")
	}

	if mmDeleteEvent.defaultExpectation == nil {
		mmDeleteEvent.defaultExpectation = &EventsMockDeleteEventExpectation{}
	}

	if mmDeleteEvent.defaultExpectation.params != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Expect")
	}

	if mmDeleteEvent.defaultExpectation.paramPtrs == nil {
		mmDeleteEvent.defaultExpectation.paramPtrs = &EventsMockDeleteEventParamPtrs{}
	}
	mmDeleteEvent.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteEvent.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteEvent
}

// ExpectEventIDParam2 sets up expected param eventID for Events.DeleteEvent
func (mmDeleteEvent *mEventsMockDeleteEvent) ExpectEventIDParam2(eventID int64) *mEventsMockDeleteEvent {
	if mmDeleteEvent.mock.funcDeleteEvent != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Set")
	}

	if mmDeleteEvent.defaultExpectation == nil {
		mmDeleteEvent.defaultExpectation = &EventsMockDeleteEventExpectation{}
	}

	if mmDeleteEvent.defaultExpectation.params != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Expect")
	}

	if mmDeleteEvent.defaultExpectation.paramPtrs == nil {
		mmDeleteEvent.defaultExpectation.paramPtrs = &EventsMockDeleteEventParamPtrs{}
	}
	mmDeleteEvent.defaultExpectation.paramPtrs.eventID = &eventID
	mmDeleteEvent.defaultExpectation.expectationOrigins.originEventID = minimock.CallerInfo(1)

	return mmDeleteEvent
}

// Inspect accepts an inspector function that has same arguments as the Events.DeleteEvent
func (mmDeleteEvent *mEventsMockDeleteEvent) Inspect(f func(userID int64, eventID int64)) *mEventsMockDeleteEvent {
	if mmDeleteEvent.mock.inspectFuncDeleteEvent != nil {
		mmDeleteEvent.mock.t.Fatalf("Inspect function is already set for EventsMock.DeleteEvent")
	}

	mmDeleteEvent.mock.inspectFuncDeleteEvent = f

	return mmDeleteEvent
}

// Return sets up results that will be returned by Events.DeleteEvent
func (mmDeleteEvent *mEventsMockDeleteEvent) Return(err error) *EventsMock {
	if mmDeleteEvent.mock.funcDeleteEvent != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Set")
	}

	if mmDeleteEvent.defaultExpectation == nil {
		mmDeleteEvent.defaultExpectation = &EventsMockDeleteEventExpectation{mock: mmDeleteEvent.mock}
	}
	mmDeleteEvent.defaultExpectation.results = &EventsMockDeleteEventResults{err}
	mmDeleteEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteEvent.mock
}

// Set uses given function f to mock the Events.DeleteEvent method
func (mmDeleteEvent *mEventsMockDeleteEvent) Set(f func(userID int64, eventID int64) (err error)) *EventsMock {
	if mmDeleteEvent.defaultExpectation != nil {
		mmDeleteEvent.mock.t.Fatalf("Default expectation is already set for the Events.DeleteEvent method")
	}

	if len(mmDeleteEvent.expectations) > 0 {
		mmDeleteEvent.mock.t.Fatalf("Some expectations are already set for the Events.DeleteEvent method")
	}

	mmDeleteEvent.mock.funcDeleteEvent = f
	mmDeleteEvent.mock.funcDeleteEventOrigin = minimock.CallerInfo(1)
	return mmDeleteEvent.mock
}

// When sets expectation for the Events.DeleteEvent which will trigger the result defined by the following
// Then helper
func (mmDeleteEvent *mEventsMockDeleteEvent) When(userID int64, eventID int64) *EventsMockDeleteEventExpectation {
	if mmDeleteEvent.mock.funcDeleteEvent != nil {
		mmDeleteEvent.mock.t.Fatalf("EventsMock.DeleteEvent mock is already set by Set")
	}

	expectation := &EventsMockDeleteEventExpectation{
		mock:               mmDeleteEvent.mock,
		params:             &EventsMockDeleteEventParams{userID, eventID},
		expectationOrigins: EventsMockDeleteEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteEvent.expectations = append(mmDeleteEvent.expectations, expectation)
	return expectation
}

// Then sets up Events.DeleteEvent return parameters for the expectation previously defined by the When method
func (e *EventsMockDeleteEventExpectation) Then(err error) *EventsMock {
	e.results = &EventsMockDeleteEventResults{err}
	return e.mock
}

// Times sets number of times Events.DeleteEvent should be invoked
func (mmDeleteEvent *mEventsMockDeleteEvent) Times(n uint64) *mEventsMockDeleteEvent {
	if n == 0 {
		mmDeleteEvent.mock.t.Fatalf("Times of EventsMock.DeleteEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteEvent.expectedInvocations, n)
	mmDeleteEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteEvent
}

func (mmDeleteEvent *mEventsMockDeleteEvent) invocationsDone() bool {
	if len(mmDeleteEvent.expectations) == 0 && mmDeleteEvent.defaultExpectation == nil && mmDeleteEvent.mock.funcDeleteEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteEvent.mock.afterDeleteEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteEvent implements mm_repositories.Events
func (mmDeleteEvent *EventsMock) DeleteEvent(userID int64, eventID int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteEvent.beforeDeleteEventCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteEvent.afterDeleteEventCounter, 1)

	mmDeleteEvent.t.Helper()

	if mmDeleteEvent.inspectFuncDeleteEvent != nil {
		mmDeleteEvent.inspectFuncDeleteEvent(userID, eventID)
	}

	mm_params := EventsMockDeleteEventParams{userID, eventID}

	// Record call args
	mmDeleteEvent.DeleteEventMock.mutex.Lock()
	mmDeleteEvent.DeleteEventMock.callArgs = append(mmDeleteEvent.DeleteEventMock.callArgs, &mm_params)
	mmDeleteEvent.DeleteEventMock.mutex.Unlock()

	for _, e := range mmDeleteEvent.DeleteEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteEvent.DeleteEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteEvent.DeleteEventMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteEvent.DeleteEventMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteEvent.DeleteEventMock.defaultExpectation.paramPtrs

		mm_got := EventsMockDeleteEventParams{userID, eventID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteEvent.t.Errorf("EventsMock.DeleteEvent got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteEvent.DeleteEventMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.eventID != nil && !minimock.Equal(*mm_want_ptrs.eventID, mm_got.eventID) {
				mmDeleteEvent.t.Errorf("EventsMock.DeleteEvent got unexpected parameter eventID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteEvent.DeleteEventMock.defaultExpectation.expectationOrigins.originEventID, *mm_want_ptrs.eventID, mm_got.eventID, minimock.Diff(*mm_want_ptrs.eventID, mm_got.eventID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteEvent.t.Errorf("EventsMock.DeleteEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteEvent.DeleteEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteEvent.DeleteEventMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteEvent.t.Fatal("No results are set for the EventsMock.DeleteEvent")
		}
		return (*mm_results).err
	}
	if mmDeleteEvent.funcDeleteEvent != nil {
		return mmDeleteEvent.funcDeleteEvent(userID, eventID)
	}
	mmDeleteEvent.t.Fatalf("Unexpected call to EventsMock.DeleteEvent. %v %v", userID, eventID)
	return
}

// DeleteEventAfterCounter returns a count of finished EventsMock.DeleteEvent invocations
func (mmDeleteEvent *EventsMock) DeleteEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteEvent.afterDeleteEventCounter)
}

// DeleteEventBeforeCounter returns a count of EventsMock.DeleteEvent invocations
func (mmDeleteEvent *EventsMock) DeleteEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteEvent.beforeDeleteEventCounter)
}

// Calls returns a list of arguments used in each call to EventsMock.DeleteEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteEvent *mEventsMockDeleteEvent) Calls() []*EventsMockDeleteEventParams {
	mmDeleteEvent.mutex.RLock()

	argCopy := make([]*EventsMockDeleteEventParams, len(mmDeleteEvent.callArgs))
	copy(argCopy, mmDeleteEvent.callArgs)

	mmDeleteEvent.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteEventDone returns true if the count of the DeleteEvent invocations corresponds
// the number of defined expectations
func (m *EventsMock) MinimockDeleteEventDone() bool {
	if m.DeleteEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteEventMock.invocationsDone()
}

// MinimockDeleteEventInspect logs each unmet expectation
func (m *EventsMock) MinimockDeleteEventInspect() {
	for _, e := range m.DeleteEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to EventsMock.DeleteEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteEventCounter := mm_atomic.LoadUint64(&m.afterDeleteEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteEventMock.defaultExpectation != nil && afterDeleteEventCounter < 1 {
		if m.DeleteEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to EventsMock.DeleteEvent at\n%s", m.DeleteEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to EventsMock.DeleteEvent at\n%s with params: %#v", m.DeleteEventMock.defaultExpectation.expectationOrigins.origin, *m.DeleteEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteEvent != nil && afterDeleteEventCounter < 1 {
		m.t.Errorf("Expected call to EventsMock.DeleteEvent at\n%s", m.funcDeleteEventOrigin)
	}

	if !m.DeleteEventMock.invocationsDone() && afterDeleteEventCounter > 0 {
		m.t.Errorf("Expected %d calls to EventsMock.DeleteEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteEventMock.expectedInvocations), m.DeleteEventMock.expectedInvocationsOrigin, afterDeleteEventCounter)
	}
}

type mEventsMockGetEvents struct {
	optional           bool
	mock               *EventsMock
	defaultExpectation *EventsMockGetEventsExpectation
	expectations       []*EventsMockGetEventsExpectation

	callArgs []*EventsMockGetEventsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// EventsMockGetEventsExpectation specifies expectation struct of the Events.GetEvents
type EventsMockGetEventsExpectation struct {
	mock               *EventsMock
	params             *EventsMockGetEventsParams
	paramPtrs          *EventsMockGetEventsParamPtrs
	expectationOrigins EventsMockGetEventsExpectationOrigins
	results            *EventsMockGetEventsResults
	returnOrigin       string
	Counter            uint64
}

// EventsMockGetEventsParams contains parameters of the Events.GetEvents
type EventsMockGetEventsParams struct {
	dateStart time.Time
	dateEnd   time.Time
	userID    int
}

// EventsMockGetEventsParamPtrs contains pointers to parameters of the Events.GetEvents
type EventsMockGetEventsParamPtrs struct {
	dateStart *time.Time
	dateEnd   *time.Time
	userID    *int
}

// EventsMockGetEventsResults contains results of the Events.GetEvents
type EventsMockGetEventsResults struct {
	ra1 []models.Reply
	err error
}

// EventsMockGetEventsOrigins contains origins of expectations of the Events.GetEvents
type EventsMockGetEventsExpectationOrigins struct {
	origin          string
	originDateStart string
	originDateEnd   string
	originUserID    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetEvents *mEventsMockGetEvents) Optional() *mEventsMockGetEvents {
	mmGetEvents.optional = true
	return mmGetEvents
}

// Expect sets up expected params for Events.GetEvents
func (mmGetEvents *mEventsMockGetEvents) Expect(dateStart time.Time, dateEnd time.Time, userID int) *mEventsMockGetEvents {
	if mmGetEvents.mock.funcGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Set")
	}

	if mmGetEvents.defaultExpectation == nil {
		mmGetEvents.defaultExpectation = &EventsMockGetEventsExpectation{}
	}

	if mmGetEvents.defaultExpectation.paramPtrs != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by ExpectParams functions")
	}

	mmGetEvents.defaultExpectation.params = &EventsMockGetEventsParams{dateStart, dateEnd, userID}
	mmGetEvents.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetEvents.expectations {
		if minimock.Equal(e.params, mmGetEvents.defaultExpectation.params) {
			mmGetEvents.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetEvents.defaultExpectation.params)
		}
	}

	return mmGetEvents
}

// ExpectDateStartParam1 sets up expected param dateStart for Events.GetEvents
func (mmGetEvents *mEventsMockGetEvents) ExpectDateStartParam1(dateStart time.Time) *mEventsMockGetEvents {
	if mmGetEvents.mock.funcGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Set")
	}

	if mmGetEvents.defaultExpectation == nil {
		mmGetEvents.defaultExpectation = &EventsMockGetEventsExpectation{}
	}

	if mmGetEvents.defaultExpectation.params != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Expect")
	}

	if mmGetEvents.defaultExpectation.paramPtrs == nil {
		mmGetEvents.defaultExpectation.paramPtrs = &EventsMockGetEventsParamPtrs{}
	}
	mmGetEvents.defaultExpectation.paramPtrs.dateStart = &dateStart
	mmGetEvents.defaultExpectation.expectationOrigins.originDateStart = minimock.CallerInfo(1)

	return mmGetEvents
}

// ExpectDateEndParam2 sets up expected param dateEnd for Events.GetEvents
func (mmGetEvents *mEventsMockGetEvents) ExpectDateEndParam2(dateEnd time.Time) *mEventsMockGetEvents {
	if mmGetEvents.mock.funcGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Set")
	}

	if mmGetEvents.defaultExpectation == nil {
		mmGetEvents.defaultExpectation = &EventsMockGetEventsExpectation{}
	}

	if mmGetEvents.defaultExpectation.params != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Expect")
	}

	if mmGetEvents.defaultExpectation.paramPtrs == nil {
		mmGetEvents.defaultExpectation.paramPtrs = &EventsMockGetEventsParamPtrs{}
	}
	mmGetEvents.defaultExpectation.paramPtrs.dateEnd = &dateEnd
	mmGetEvents.defaultExpectation.expectationOrigins.originDateEnd = minimock.CallerInfo(1)

	return mmGetEvents
}

// ExpectUserIDParam3 sets up expected param userID for Events.GetEvents
func (mmGetEvents *mEventsMockGetEvents) ExpectUserIDParam3(userID int) *mEventsMockGetEvents {
	if mmGetEvents.mock.funcGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Set")
	}

	if mmGetEvents.defaultExpectation == nil {
		mmGetEvents.defaultExpectation = &EventsMockGetEventsExpectation{}
	}

	if mmGetEvents.defaultExpectation.params != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Expect")
	}

	if mmGetEvents.defaultExpectation.paramPtrs == nil {
		mmGetEvents.defaultExpectation.paramPtrs = &EventsMockGetEventsParamPtrs{}
	}
	mmGetEvents.defaultExpectation.paramPtrs.userID = &userID
	mmGetEvents.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetEvents
}

// Inspect accepts an inspector function that has same arguments as the Events.GetEvents
func (mmGetEvents *mEventsMockGetEvents) Inspect(f func(dateStart time.Time, dateEnd time.Time, userID int)) *mEventsMockGetEvents {
	if mmGetEvents.mock.inspectFuncGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("Inspect function is already set for EventsMock.GetEvents")
	}

	mmGetEvents.mock.inspectFuncGetEvents = f

	return mmGetEvents
}

// Return sets up results that will be returned by Events.GetEvents
func (mmGetEvents *mEventsMockGetEvents) Return(ra1 []models.Reply, err error) *EventsMock {
	if mmGetEvents.mock.funcGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Set")
	}

	if mmGetEvents.defaultExpectation == nil {
		mmGetEvents.defaultExpectation = &EventsMockGetEventsExpectation{mock: mmGetEvents.mock}
	}
	mmGetEvents.defaultExpectation.results = &EventsMockGetEventsResults{ra1, err}
	mmGetEvents.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetEvents.mock
}

// Set uses given function f to mock the Events.GetEvents method
func (mmGetEvents *mEventsMockGetEvents) Set(f func(dateStart time.Time, dateEnd time.Time, userID int) (ra1 []models.Reply, err error)) *EventsMock {
	if mmGetEvents.defaultExpectation != nil {
		mmGetEvents.mock.t.Fatalf("Default expectation is already set for the Events.GetEvents method")
	}

	if len(mmGetEvents.expectations) > 0 {
		mmGetEvents.mock.t.Fatalf("Some expectations are already set for the Events.GetEvents method")
	}

	mmGetEvents.mock.funcGetEvents = f
	mmGetEvents.mock.funcGetEventsOrigin = minimock.CallerInfo(1)
	return mmGetEvents.mock
}

// When sets expectation for the Events.GetEvents which will trigger the result defined by the following
// Then helper
func (mmGetEvents *mEventsMockGetEvents) When(dateStart time.Time, dateEnd time.Time, userID int) *EventsMockGetEventsExpectation {
	if mmGetEvents.mock.funcGetEvents != nil {
		mmGetEvents.mock.t.Fatalf("EventsMock.GetEvents mock is already set by Set")
	}

	expectation := &EventsMockGetEventsExpectation{
		mock:               mmGetEvents.mock,
		params:             &EventsMockGetEventsParams{dateStart, dateEnd, userID},
		expectationOrigins: EventsMockGetEventsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetEvents.expectations = append(mmGetEvents.expectations, expectation)
	return expectation
}

// Then sets up Events.GetEvents return parameters for the expectation previously defined by the When method
func (e *EventsMockGetEventsExpectation) Then(ra1 []models.Reply, err error) *EventsMock {
	e.results = &EventsMockGetEventsResults{ra1, err}
	return e.mock
}

// Times sets number of times Events.GetEvents should be invoked
func (mmGetEvents *mEventsMockGetEvents) Times(n uint64) *mEventsMockGetEvents {
	if n == 0 {
		mmGetEvents.mock.t.Fatalf("Times of EventsMock.GetEvents mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetEvents.expectedInvocations, n)
	mmGetEvents.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetEvents
}

func (mmGetEvents *mEventsMockGetEvents) invocationsDone() bool {
	if len(mmGetEvents.expectations) == 0 && mmGetEvents.defaultExpectation == nil && mmGetEvents.mock.funcGetEvents == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetEvents.mock.afterGetEventsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetEvents.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetEvents implements mm_repositories.Events
func (mmGetEvents *EventsMock) GetEvents(dateStart time.Time, dateEnd time.Time, userID int) (ra1 []models.Reply, err error) {
	mm_atomic.AddUint64(&mmGetEvents.beforeGetEventsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetEvents.afterGetEventsCounter, 1)

	mmGetEvents.t.Helper()

	if mmGetEvents.inspectFuncGetEvents != nil {
		mmGetEvents.inspectFuncGetEvents(dateStart, dateEnd, userID)
	}

	mm_params := EventsMockGetEventsParams{dateStart, dateEnd, userID}

	// Record call args
	mmGetEvents.GetEventsMock.mutex.Lock()
	mmGetEvents.GetEventsMock.callArgs = append(mmGetEvents.GetEventsMock.callArgs, &mm_params)
	mmGetEvents.GetEventsMock.mutex.Unlock()

	for _, e := range mmGetEvents.GetEventsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ra1, e.results.err
		}
	}

	if mmGetEvents.GetEventsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetEvents.GetEventsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetEvents.GetEventsMock.defaultExpectation.params
		mm_want_ptrs := mmGetEvents.GetEventsMock.defaultExpectation.paramPtrs

		mm_got := EventsMockGetEventsParams{dateStart, dateEnd, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.dateStart != nil && !minimock.Equal(*mm_want_ptrs.dateStart, mm_got.dateStart) {
				mmGetEvents.t.Errorf("EventsMock.GetEvents got unexpected parameter dateStart, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetEvents.GetEventsMock.defaultExpectation.expectationOrigins.originDateStart, *mm_want_ptrs.dateStart, mm_got.dateStart, minimock.Diff(*mm_want_ptrs.dateStart, mm_got.dateStart))
			}

			if mm_want_ptrs.dateEnd != nil && !minimock.Equal(*mm_want_ptrs.dateEnd, mm_got.dateEnd) {
				mmGetEvents.t.Errorf("EventsMock.GetEvents got unexpected parameter dateEnd, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetEvents.GetEventsMock.defaultExpectation.expectationOrigins.originDateEnd, *mm_want_ptrs.dateEnd, mm_got.dateEnd, minimock.Diff(*mm_want_ptrs.dateEnd, mm_got.dateEnd))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetEvents.t.Errorf("EventsMock.GetEvents got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetEvents.GetEventsMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetEvents.t.Errorf("EventsMock.GetEvents got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetEvents.GetEventsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetEvents.GetEventsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetEvents.t.Fatal("No results are set for the EventsMock.GetEvents")
		}
		return (*mm_results).ra1, (*mm_results).err
	}
	if mmGetEvents.funcGetEvents != nil {
		return mmGetEvents.funcGetEvents(dateStart, dateEnd, userID)
	}
	mmGetEvents.t.Fatalf("Unexpected call to EventsMock.GetEvents. %v %v %v", dateStart, dateEnd, userID)
	return
}

// GetEventsAfterCounter returns a count of finished EventsMock.GetEvents invocations
func (mmGetEvents *EventsMock) GetEventsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetEvents.afterGetEventsCounter)
}

// GetEventsBeforeCounter returns a count of EventsMock.GetEvents invocations
func (mmGetEvents *EventsMock) GetEventsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetEvents.beforeGetEventsCounter)
}

// Calls returns a list of arguments used in each call to EventsMock.GetEvents.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetEvents *mEventsMockGetEvents) Calls() []*EventsMockGetEventsParams {
	mmGetEvents.mutex.RLock()

	argCopy := make([]*EventsMockGetEventsParams, len(mmGetEvents.callArgs))
	copy(argCopy, mmGetEvents.callArgs)

	mmGetEvents.mutex.RUnlock()

	return argCopy
}

// MinimockGetEventsDone returns true if the count of the GetEvents invocations corresponds
// the number of defined expectations
func (m *EventsMock) MinimockGetEventsDone() bool {
	if m.GetEventsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetEventsMock.invocationsDone()
}

// MinimockGetEventsInspect logs each unmet expectation
func (m *EventsMock) MinimockGetEventsInspect() {
	for _, e := range m.GetEventsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to EventsMock.GetEvents at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetEventsCounter := mm_atomic.LoadUint64(&m.afterGetEventsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetEventsMock.defaultExpectation != nil && afterGetEventsCounter < 1 {
		if m.GetEventsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to EventsMock.GetEvents at\n%s", m.GetEventsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to EventsMock.GetEvents at\n%s with params: %#v", m.GetEventsMock.defaultExpectation.expectationOrigins.origin, *m.GetEventsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetEvents != nil && afterGetEventsCounter < 1 {
		m.t.Errorf("Expected call to EventsMock.GetEvents at\n%s", m.funcGetEventsOrigin)
	}

	if !m.GetEventsMock.invocationsDone() && afterGetEventsCounter > 0 {
		m.t.Errorf("Expected %d calls to EventsMock.GetEvents at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetEventsMock.expectedInvocations), m.GetEventsMock.expectedInvocationsOrigin, afterGetEventsCounter)
	}
}

type mEventsMockNewEvent struct {
	optional           bool
	mock               *EventsMock
	defaultExpectation *EventsMockNewEventExpectation
	expectations       []*EventsMockNewEventExpectation

	callArgs []*EventsMockNewEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// EventsMockNewEventExpectation specifies expectation struct of the Events.NewEvent
type EventsMockNewEventExpectation struct {
	mock               *EventsMock
	params             *EventsMockNewEventParams
	paramPtrs          *EventsMockNewEventParamPtrs
	expectationOrigins EventsMockNewEventExpectationOrigins
	results            *EventsMockNewEventResults
	returnOrigin       string
	Counter            uint64
}

// EventsMockNewEventParams contains parameters of the Events.NewEvent
type EventsMockNewEventParams struct {
	userId int64
	event  models.Event
}

// EventsMockNewEventParamPtrs contains pointers to parameters of the Events.NewEvent
type EventsMockNewEventParamPtrs struct {
	userId *int64
	event  *models.Event
}

// EventsMockNewEventResults contains results of the Events.NewEvent
type EventsMockNewEventResults struct {
	err error
}

// EventsMockNewEventOrigins contains origins of expectations of the Events.NewEvent
type EventsMockNewEventExpectationOrigins struct {
	origin       string
	originUserId string
	originEvent  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewEvent *mEventsMockNewEvent) Optional() *mEventsMockNewEvent {
	mmNewEvent.optional = true
	return mmNewEvent
}

// Expect sets up expected params for Events.NewEvent
func (mmNewEvent *mEventsMockNewEvent) Expect(userId int64, event models.Event) *mEventsMockNewEvent {
	if mmNewEvent.mock.funcNewEvent != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Set")
	}

	if mmNewEvent.defaultExpectation == nil {
		mmNewEvent.defaultExpectation = &EventsMockNewEventExpectation{}
	}

	if mmNewEvent.defaultExpectation.paramPtrs != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by ExpectParams functions")
	}

	mmNewEvent.defaultExpectation.params = &EventsMockNewEventParams{userId, event}
	mmNewEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmNewEvent.expectations {
		if minimock.Equal(e.params, mmNewEvent.defaultExpectation.params) {
			mmNewEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNewEvent.defaultExpectation.params)
		}
	}

	return mmNewEvent
}

// ExpectUserIdParam1 sets up expected param userId for Events.NewEvent
func (mmNewEvent *mEventsMockNewEvent) ExpectUserIdParam1(userId int64) *mEventsMockNewEvent {
	if mmNewEvent.mock.funcNewEvent != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Set")
	}

	if mmNewEvent.defaultExpectation == nil {
		mmNewEvent.defaultExpectation = &EventsMockNewEventExpectation{}
	}

	if mmNewEvent.defaultExpectation.params != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Expect")
	}

	if mmNewEvent.defaultExpectation.paramPtrs == nil {
		mmNewEvent.defaultExpectation.paramPtrs = &EventsMockNewEventParamPtrs{}
	}
	mmNewEvent.defaultExpectation.paramPtrs.userId = &userId
	mmNewEvent.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmNewEvent
}

// ExpectEventParam2 sets up expected param event for Events.NewEvent
func (mmNewEvent *mEventsMockNewEvent) ExpectEventParam2(event models.Event) *mEventsMockNewEvent {
	if mmNewEvent.mock.funcNewEvent != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Set")
	}

	if mmNewEvent.defaultExpectation == nil {
		mmNewEvent.defaultExpectation = &EventsMockNewEventExpectation{}
	}

	if mmNewEvent.defaultExpectation.params != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Expect")
	}

	if mmNewEvent.defaultExpectation.paramPtrs == nil {
		mmNewEvent.defaultExpectation.paramPtrs = &EventsMockNewEventParamPtrs{}
	}
	mmNewEvent.defaultExpectation.paramPtrs.event = &event
	mmNewEvent.defaultExpectation.expectationOrigins.originEvent = minimock.CallerInfo(1)

	return mmNewEvent
}

// Inspect accepts an inspector function that has same arguments as the Events.NewEvent
func (mmNewEvent *mEventsMockNewEvent) Inspect(f func(userId int64, event models.Event)) *mEventsMockNewEvent {
	if mmNewEvent.mock.inspectFuncNewEvent != nil {
		mmNewEvent.mock.t.Fatalf("Inspect function is already set for EventsMock.NewEvent")
	}

	mmNewEvent.mock.inspectFuncNewEvent = f

	return mmNewEvent
}

// Return sets up results that will be returned by Events.NewEvent
func (mmNewEvent *mEventsMockNewEvent) Return(err error) *EventsMock {
	if mmNewEvent.mock.funcNewEvent != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Set")
	}

	if mmNewEvent.defaultExpectation == nil {
		mmNewEvent.defaultExpectation = &EventsMockNewEventExpectation{mock: mmNewEvent.mock}
	}
	mmNewEvent.defaultExpectation.results = &EventsMockNewEventResults{err}
	mmNewEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewEvent.mock
}

// Set uses given function f to mock the Events.NewEvent method
func (mmNewEvent *mEventsMockNewEvent) Set(f func(userId int64, event models.Event) (err error)) *EventsMock {
	if mmNewEvent.defaultExpectation != nil {
		mmNewEvent.mock.t.Fatalf("Default expectation is already set for the Events.NewEvent method")
	}

	if len(mmNewEvent.expectations) > 0 {
		mmNewEvent.mock.t.Fatalf("Some expectations are already set for the Events.NewEvent method")
	}

	mmNewEvent.mock.funcNewEvent = f
	mmNewEvent.mock.funcNewEventOrigin = minimock.CallerInfo(1)
	return mmNewEvent.mock
}

// When sets expectation for the Events.NewEvent which will trigger the result defined by the following
// Then helper
func (mmNewEvent *mEventsMockNewEvent) When(userId int64, event models.Event) *EventsMockNewEventExpectation {
	if mmNewEvent.mock.funcNewEvent != nil {
		mmNewEvent.mock.t.Fatalf("EventsMock.NewEvent mock is already set by Set")
	}

	expectation := &EventsMockNewEventExpectation{
		mock:               mmNewEvent.mock,
		params:             &EventsMockNewEventParams{userId, event},
		expectationOrigins: EventsMockNewEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmNewEvent.expectations = append(mmNewEvent.expectations, expectation)
	return expectation
}

// Then sets up Events.NewEvent return parameters for the expectation previously defined by the When method
func (e *EventsMockNewEventExpectation) Then(err error) *EventsMock {
	e.results = &EventsMockNewEventResults{err}
	return e.mock
}

// Times sets number of times Events.NewEvent should be invoked
func (mmNewEvent *mEventsMockNewEvent) Times(n uint64) *mEventsMockNewEvent {
	if n == 0 {
		mmNewEvent.mock.t.Fatalf("Times of EventsMock.NewEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewEvent.expectedInvocations, n)
	mmNewEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewEvent
}

func (mmNewEvent *mEventsMockNewEvent) invocationsDone() bool {
	if len(mmNewEvent.expectations) == 0 && mmNewEvent.defaultExpectation == nil && mmNewEvent.mock.funcNewEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewEvent.mock.afterNewEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewEvent implements mm_repositories.Events
func (mmNewEvent *EventsMock) NewEvent(userId int64, event models.Event) (err error) {
	mm_atomic.AddUint64(&mmNewEvent.beforeNewEventCounter, 1)
	defer mm_atomic.AddUint64(&mmNewEvent.afterNewEventCounter, 1)

	mmNewEvent.t.Helper()

	if mmNewEvent.inspectFuncNewEvent != nil {
		mmNewEvent.inspectFuncNewEvent(userId, event)
	}

	mm_params := EventsMockNewEventParams{userId, event}

	// Record call args
	mmNewEvent.NewEventMock.mutex.Lock()
	mmNewEvent.NewEventMock.callArgs = append(mmNewEvent.NewEventMock.callArgs, &mm_params)
	mmNewEvent.NewEventMock.mutex.Unlock()

	for _, e := range mmNewEvent.NewEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmNewEvent.NewEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewEvent.NewEventMock.defaultExpectation.Counter, 1)
		mm_want := mmNewEvent.NewEventMock.defaultExpectation.params
		mm_want_ptrs := mmNewEvent.NewEventMock.defaultExpectation.paramPtrs

		mm_got := EventsMockNewEventParams{userId, event}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmNewEvent.t.Errorf("EventsMock.NewEvent got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewEvent.NewEventMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.event != nil && !minimock.Equal(*mm_want_ptrs.event, mm_got.event) {
				mmNewEvent.t.Errorf("EventsMock.NewEvent got unexpected parameter event, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewEvent.NewEventMock.defaultExpectation.expectationOrigins.originEvent, *mm_want_ptrs.event, mm_got.event, minimock.Diff(*mm_want_ptrs.event, mm_got.event))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNewEvent.t.Errorf("EventsMock.NewEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmNewEvent.NewEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNewEvent.NewEventMock.defaultExpectation.results
		if mm_results == nil {
			mmNewEvent.t.Fatal("No results are set for the EventsMock.NewEvent")
		}
		return (*mm_results).err
	}
	if mmNewEvent.funcNewEvent != nil {
		return mmNewEvent.funcNewEvent(userId, event)
	}
	mmNewEvent.t.Fatalf("Unexpected call to EventsMock.NewEvent. %v %v", userId, event)
	return
}

// NewEventAfterCounter returns a count of finished EventsMock.NewEvent invocations
func (mmNewEvent *EventsMock) NewEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewEvent.afterNewEventCounter)
}

// NewEventBeforeCounter returns a count of EventsMock.NewEvent invocations
func (mmNewEvent *EventsMock) NewEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewEvent.beforeNewEventCounter)
}

// Calls returns a list of arguments used in each call to EventsMock.NewEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNewEvent *mEventsMockNewEvent) Calls() []*EventsMockNewEventParams {
	mmNewEvent.mutex.RLock()

	argCopy := make([]*EventsMockNewEventParams, len(mmNewEvent.callArgs))
	copy(argCopy, mmNewEvent.callArgs)

	mmNewEvent.mutex.RUnlock()

	return argCopy
}

// MinimockNewEventDone returns true if the count of the NewEvent invocations corresponds
// the number of defined expectations
func (m *EventsMock) MinimockNewEventDone() bool {
	if m.NewEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewEventMock.invocationsDone()
}

// MinimockNewEventInspect logs each unmet expectation
func (m *EventsMock) MinimockNewEventInspect() {
	for _, e := range m.NewEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to EventsMock.NewEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterNewEventCounter := mm_atomic.LoadUint64(&m.afterNewEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewEventMock.defaultExpectation != nil && afterNewEventCounter < 1 {
		if m.NewEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to EventsMock.NewEvent at\n%s", m.NewEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to EventsMock.NewEvent at\n%s with params: %#v", m.NewEventMock.defaultExpectation.expectationOrigins.origin, *m.NewEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewEvent != nil && afterNewEventCounter < 1 {
		m.t.Errorf("Expected call to EventsMock.NewEvent at\n%s", m.funcNewEventOrigin)
	}

	if !m.NewEventMock.invocationsDone() && afterNewEventCounter > 0 {
		m.t.Errorf("Expected %d calls to EventsMock.NewEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewEventMock.expectedInvocations), m.NewEventMock.expectedInvocationsOrigin, afterNewEventCounter)
	}
}

type mEventsMockUpdateEvent struct {
	optional           bool
	mock               *EventsMock
	defaultExpectation *EventsMockUpdateEventExpectation
	expectations       []*EventsMockUpdateEventExpectation

	callArgs []*EventsMockUpdateEventParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// EventsMockUpdateEventExpectation specifies expectation struct of the Events.UpdateEvent
type EventsMockUpdateEventExpectation struct {
	mock               *EventsMock
	params             *EventsMockUpdateEventParams
	paramPtrs          *EventsMockUpdateEventParamPtrs
	expectationOrigins EventsMockUpdateEventExpectationOrigins
	results            *EventsMockUpdateEventResults
	returnOrigin       string
	Counter            uint64
}

// EventsMockUpdateEventParams contains parameters of the Events.UpdateEvent
type EventsMockUpdateEventParams struct {
	userID  int64
	eventID int64
	input   models.UpdateEvent
}

// EventsMockUpdateEventParamPtrs contains pointers to parameters of the Events.UpdateEvent
type EventsMockUpdateEventParamPtrs struct {
	userID  *int64
	eventID *int64
	input   *models.UpdateEvent
}

// EventsMockUpdateEventResults contains results of the Events.UpdateEvent
type EventsMockUpdateEventResults struct {
	err error
}

// EventsMockUpdateEventOrigins contains origins of expectations of the Events.UpdateEvent
type EventsMockUpdateEventExpectationOrigins struct {
	origin        string
	originUserID  string
	originEventID string
	originInput   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateEvent *mEventsMockUpdateEvent) Optional() *mEventsMockUpdateEvent {
	mmUpdateEvent.optional = true
	return mmUpdateEvent
}

// Expect sets up expected params for Events.UpdateEvent
func (mmUpdateEvent *mEventsMockUpdateEvent) Expect(userID int64, eventID int64, input models.UpdateEvent) *mEventsMockUpdateEvent {
	if mmUpdateEvent.mock.funcUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Set")
	}

	if mmUpdateEvent.defaultExpectation == nil {
		mmUpdateEvent.defaultExpectation = &EventsMockUpdateEventExpectation{}
	}

	if mmUpdateEvent.defaultExpectation.paramPtrs != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by ExpectParams functions")
	}

	mmUpdateEvent.defaultExpectation.params = &EventsMockUpdateEventParams{userID, eventID, input}
	mmUpdateEvent.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateEvent.expectations {
		if minimock.Equal(e.params, mmUpdateEvent.defaultExpectation.params) {
			mmUpdateEvent.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateEvent.defaultExpectation.params)
		}
	}

	return mmUpdateEvent
}

// ExpectUserIDParam1 sets up expected param userID for Events.UpdateEvent
func (mmUpdateEvent *mEventsMockUpdateEvent) ExpectUserIDParam1(userID int64) *mEventsMockUpdateEvent {
	if mmUpdateEvent.mock.funcUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Set")
	}

	if mmUpdateEvent.defaultExpectation == nil {
		mmUpdateEvent.defaultExpectation = &EventsMockUpdateEventExpectation{}
	}

	if mmUpdateEvent.defaultExpectation.params != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Expect")
	}

	if mmUpdateEvent.defaultExpectation.paramPtrs == nil {
		mmUpdateEvent.defaultExpectation.paramPtrs = &EventsMockUpdateEventParamPtrs{}
	}
	mmUpdateEvent.defaultExpectation.paramPtrs.userID = &userID
	mmUpdateEvent.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmUpdateEvent
}

// ExpectEventIDParam2 sets up expected param eventID for Events.UpdateEvent
func (mmUpdateEvent *mEventsMockUpdateEvent) ExpectEventIDParam2(eventID int64) *mEventsMockUpdateEvent {
	if mmUpdateEvent.mock.funcUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Set")
	}

	if mmUpdateEvent.defaultExpectation == nil {
		mmUpdateEvent.defaultExpectation = &EventsMockUpdateEventExpectation{}
	}

	if mmUpdateEvent.defaultExpectation.params != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Expect")
	}

	if mmUpdateEvent.defaultExpectation.paramPtrs == nil {
		mmUpdateEvent.defaultExpectation.paramPtrs = &EventsMockUpdateEventParamPtrs{}
	}
	mmUpdateEvent.defaultExpectation.paramPtrs.eventID = &eventID
	mmUpdateEvent.defaultExpectation.expectationOrigins.originEventID = minimock.CallerInfo(1)

	return mmUpdateEvent
}

// ExpectInputParam3 sets up expected param input for Events.UpdateEvent
func (mmUpdateEvent *mEventsMockUpdateEvent) ExpectInputParam3(input models.UpdateEvent) *mEventsMockUpdateEvent {
	if mmUpdateEvent.mock.funcUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Set")
	}

	if mmUpdateEvent.defaultExpectation == nil {
		mmUpdateEvent.defaultExpectation = &EventsMockUpdateEventExpectation{}
	}

	if mmUpdateEvent.defaultExpectation.params != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Expect")
	}

	if mmUpdateEvent.defaultExpectation.paramPtrs == nil {
		mmUpdateEvent.defaultExpectation.paramPtrs = &EventsMockUpdateEventParamPtrs{}
	}
	mmUpdateEvent.defaultExpectation.paramPtrs.input = &input
	mmUpdateEvent.defaultExpectation.expectationOrigins.originInput = minimock.CallerInfo(1)

	return mmUpdateEvent
}

// Inspect accepts an inspector function that has same arguments as the Events.UpdateEvent
func (mmUpdateEvent *mEventsMockUpdateEvent) Inspect(f func(userID int64, eventID int64, input models.UpdateEvent)) *mEventsMockUpdateEvent {
	if mmUpdateEvent.mock.inspectFuncUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("Inspect function is already set for EventsMock.UpdateEvent")
	}

	mmUpdateEvent.mock.inspectFuncUpdateEvent = f

	return mmUpdateEvent
}

// Return sets up results that will be returned by Events.UpdateEvent
func (mmUpdateEvent *mEventsMockUpdateEvent) Return(err error) *EventsMock {
	if mmUpdateEvent.mock.funcUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Set")
	}

	if mmUpdateEvent.defaultExpectation == nil {
		mmUpdateEvent.defaultExpectation = &EventsMockUpdateEventExpectation{mock: mmUpdateEvent.mock}
	}
	mmUpdateEvent.defaultExpectation.results = &EventsMockUpdateEventResults{err}
	mmUpdateEvent.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateEvent.mock
}

// Set uses given function f to mock the Events.UpdateEvent method
func (mmUpdateEvent *mEventsMockUpdateEvent) Set(f func(userID int64, eventID int64, input models.UpdateEvent) (err error)) *EventsMock {
	if mmUpdateEvent.defaultExpectation != nil {
		mmUpdateEvent.mock.t.Fatalf("Default expectation is already set for the Events.UpdateEvent method")
	}

	if len(mmUpdateEvent.expectations) > 0 {
		mmUpdateEvent.mock.t.Fatalf("Some expectations are already set for the Events.UpdateEvent method")
	}

	mmUpdateEvent.mock.funcUpdateEvent = f
	mmUpdateEvent.mock.funcUpdateEventOrigin = minimock.CallerInfo(1)
	return mmUpdateEvent.mock
}

// When sets expectation for the Events.UpdateEvent which will trigger the result defined by the following
// Then helper
func (mmUpdateEvent *mEventsMockUpdateEvent) When(userID int64, eventID int64, input models.UpdateEvent) *EventsMockUpdateEventExpectation {
	if mmUpdateEvent.mock.funcUpdateEvent != nil {
		mmUpdateEvent.mock.t.Fatalf("EventsMock.UpdateEvent mock is already set by Set")
	}

	expectation := &EventsMockUpdateEventExpectation{
		mock:               mmUpdateEvent.mock,
		params:             &EventsMockUpdateEventParams{userID, eventID, input},
		expectationOrigins: EventsMockUpdateEventExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateEvent.expectations = append(mmUpdateEvent.expectations, expectation)
	return expectation
}

// Then sets up Events.UpdateEvent return parameters for the expectation previously defined by the When method
func (e *EventsMockUpdateEventExpectation) Then(err error) *EventsMock {
	e.results = &EventsMockUpdateEventResults{err}
	return e.mock
}

// Times sets number of times Events.UpdateEvent should be invoked
func (mmUpdateEvent *mEventsMockUpdateEvent) Times(n uint64) *mEventsMockUpdateEvent {
	if n == 0 {
		mmUpdateEvent.mock.t.Fatalf("Times of EventsMock.UpdateEvent mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateEvent.expectedInvocations, n)
	mmUpdateEvent.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateEvent
}

func (mmUpdateEvent *mEventsMockUpdateEvent) invocationsDone() bool {
	if len(mmUpdateEvent.expectations) == 0 && mmUpdateEvent.defaultExpectation == nil && mmUpdateEvent.mock.funcUpdateEvent == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateEvent.mock.afterUpdateEventCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateEvent.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateEvent implements mm_repositories.Events
func (mmUpdateEvent *EventsMock) UpdateEvent(userID int64, eventID int64, input models.UpdateEvent) (err error) {
	mm_atomic.AddUint64(&mmUpdateEvent.beforeUpdateEventCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateEvent.afterUpdateEventCounter, 1)

	mmUpdateEvent.t.Helper()

	if mmUpdateEvent.inspectFuncUpdateEvent != nil {
		mmUpdateEvent.inspectFuncUpdateEvent(userID, eventID, input)
	}

	mm_params := EventsMockUpdateEventParams{userID, eventID, input}

	// Record call args
	mmUpdateEvent.UpdateEventMock.mutex.Lock()
	mmUpdateEvent.UpdateEventMock.callArgs = append(mmUpdateEvent.UpdateEventMock.callArgs, &mm_params)
	mmUpdateEvent.UpdateEventMock.mutex.Unlock()

	for _, e := range mmUpdateEvent.UpdateEventMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateEvent.UpdateEventMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateEvent.UpdateEventMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateEvent.UpdateEventMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateEvent.UpdateEventMock.defaultExpectation.paramPtrs

		mm_got := EventsMockUpdateEventParams{userID, eventID, input}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmUpdateEvent.t.Errorf("EventsMock.UpdateEvent got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateEvent.UpdateEventMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.eventID != nil && !minimock.Equal(*mm_want_ptrs.eventID, mm_got.eventID) {
				mmUpdateEvent.t.Errorf("EventsMock.UpdateEvent got unexpected parameter eventID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateEvent.UpdateEventMock.defaultExpectation.expectationOrigins.originEventID, *mm_want_ptrs.eventID, mm_got.eventID, minimock.Diff(*mm_want_ptrs.eventID, mm_got.eventID))
			}

			if mm_want_ptrs.input != nil && !minimock.Equal(*mm_want_ptrs.input, mm_got.input) {
				mmUpdateEvent.t.Errorf("EventsMock.UpdateEvent got unexpected parameter input, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateEvent.UpdateEventMock.defaultExpectation.expectationOrigins.originInput, *mm_want_ptrs.input, mm_got.input, minimock.Diff(*mm_want_ptrs.input, mm_got.input))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateEvent.t.Errorf("EventsMock.UpdateEvent got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateEvent.UpdateEventMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateEvent.UpdateEventMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateEvent.t.Fatal("No results are set for the EventsMock.UpdateEvent")
		}
		return (*mm_results).err
	}
	if mmUpdateEvent.funcUpdateEvent != nil {
		return mmUpdateEvent.funcUpdateEvent(userID, eventID, input)
	}
	mmUpdateEvent.t.Fatalf("Unexpected call to EventsMock.UpdateEvent. %v %v %v", userID, eventID, input)
	return
}

// UpdateEventAfterCounter returns a count of finished EventsMock.UpdateEvent invocations
func (mmUpdateEvent *EventsMock) UpdateEventAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateEvent.afterUpdateEventCounter)
}

// UpdateEventBeforeCounter returns a count of EventsMock.UpdateEvent invocations
func (mmUpdateEvent *EventsMock) UpdateEventBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateEvent.beforeUpdateEventCounter)
}

// Calls returns a list of arguments used in each call to EventsMock.UpdateEvent.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateEvent *mEventsMockUpdateEvent) Calls() []*EventsMockUpdateEventParams {
	mmUpdateEvent.mutex.RLock()

	argCopy := make([]*EventsMockUpdateEventParams, len(mmUpdateEvent.callArgs))
	copy(argCopy, mmUpdateEvent.callArgs)

	mmUpdateEvent.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateEventDone returns true if the count of the UpdateEvent invocations corresponds
// the number of defined expectations
func (m *EventsMock) MinimockUpdateEventDone() bool {
	if m.UpdateEventMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateEventMock.invocationsDone()
}

// MinimockUpdateEventInspect logs each unmet expectation
func (m *EventsMock) MinimockUpdateEventInspect() {
	for _, e := range m.UpdateEventMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to EventsMock.UpdateEvent at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateEventCounter := mm_atomic.LoadUint64(&m.afterUpdateEventCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateEventMock.defaultExpectation != nil && afterUpdateEventCounter < 1 {
		if m.UpdateEventMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to EventsMock.UpdateEvent at\n%s", m.UpdateEventMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to EventsMock.UpdateEvent at\n%s with params: %#v", m.UpdateEventMock.defaultExpectation.expectationOrigins.origin, *m.UpdateEventMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateEvent != nil && afterUpdateEventCounter < 1 {
		m.t.Errorf("Expected call to EventsMock.UpdateEvent at\n%s", m.funcUpdateEventOrigin)
	}

	if !m.UpdateEventMock.invocationsDone() && afterUpdateEventCounter > 0 {
		m.t.Errorf("Expected %d calls to EventsMock.UpdateEvent at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateEventMock.expectedInvocations), m.UpdateEventMock.expectedInvocationsOrigin, afterUpdateEventCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *EventsMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteEventInspect()

			m.MinimockGetEventsInspect()

			m.MinimockNewEventInspect()

			m.MinimockUpdateEventInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *EventsMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *EventsMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteEventDone() &&
		m.MinimockGetEventsDone() &&
		m.MinimockNewEventDone() &&
		m.MinimockUpdateEventDone()
}
