// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/znmaster911/L2-calendar/pkg/repositories.Users -o users_mock.go -n UsersMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UsersMock implements mm_repositories.Users
type UsersMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLogIn          func(username string) (i1 int64, err error)
	funcLogInOrigin    string
	inspectFuncLogIn   func(username string)
	afterLogInCounter  uint64
	beforeLogInCounter uint64
	LogInMock          mUsersMockLogIn

	funcNewUser          func(s1 string) (i1 int64, err error)
	funcNewUserOrigin    string
	inspectFuncNewUser   func(s1 string)
	afterNewUserCounter  uint64
	beforeNewUserCounter uint64
	NewUserMock          mUsersMockNewUser

	funcUserExists          func(username string) (b1 bool, err error)
	funcUserExistsOrigin    string
	inspectFuncUserExists   func(username string)
	afterUserExistsCounter  uint64
	beforeUserExistsCounter uint64
	UserExistsMock          mUsersMockUserExists
}

// NewUsersMock returns a mock for mm_repositories.Users
func NewUsersMock(t minimock.Tester) *UsersMock {
	m := &UsersMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LogInMock = mUsersMockLogIn{mock: m}
	m.LogInMock.callArgs = []*UsersMockLogInParams{}

	m.NewUserMock = mUsersMockNewUser{mock: m}
	m.NewUserMock.callArgs = []*UsersMockNewUserParams{}

	m.UserExistsMock = mUsersMockUserExists{mock: m}
	m.UserExistsMock.callArgs = []*UsersMockUserExistsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUsersMockLogIn struct {
	optional           bool
	mock               *UsersMock
	defaultExpectation *UsersMockLogInExpectation
	expectations       []*UsersMockLogInExpectation

	callArgs []*UsersMockLogInParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersMockLogInExpectation specifies expectation struct of the Users.LogIn
type UsersMockLogInExpectation struct {
	mock               *UsersMock
	params             *UsersMockLogInParams
	paramPtrs          *UsersMockLogInParamPtrs
	expectationOrigins UsersMockLogInExpectationOrigins
	results            *UsersMockLogInResults
	returnOrigin       string
	Counter            uint64
}

// UsersMockLogInParams contains parameters of the Users.LogIn
type UsersMockLogInParams struct {
	username string
}

// UsersMockLogInParamPtrs contains pointers to parameters of the Users.LogIn
type UsersMockLogInParamPtrs struct {
	username *string
}

// UsersMockLogInResults contains results of the Users.LogIn
type UsersMockLogInResults struct {
	i1  int64
	err error
}

// UsersMockLogInOrigins contains origins of expectations of the Users.LogIn
type UsersMockLogInExpectationOrigins struct {
	origin         string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLogIn *mUsersMockLogIn) Optional() *mUsersMockLogIn {
	mmLogIn.optional = true
	return mmLogIn
}

// Expect sets up expected params for Users.LogIn
func (mmLogIn *mUsersMockLogIn) Expect(username string) *mUsersMockLogIn {
	if mmLogIn.mock.funcLogIn != nil {
		mmLogIn.mock.t.Fatalf("UsersMock.LogIn mock is already set by Set")
	}

	if mmLogIn.defaultExpectation == nil {
		mmLogIn.defaultExpectation = &UsersMockLogInExpectation{}
	}

	if mmLogIn.defaultExpectation.paramPtrs != nil {
		mmLogIn.mock.t.Fatalf("UsersMock.LogIn mock is already set by ExpectParams functions")
	}

	mmLogIn.defaultExpectation.params = &UsersMockLogInParams{username}
	mmLogIn.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLogIn.expectations {
		if minimock.Equal(e.params, mmLogIn.defaultExpectation.params) {
			mmLogIn.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLogIn.defaultExpectation.params)
		}
	}

	return mmLogIn
}

// ExpectUsernameParam1 sets up expected param username for Users.LogIn
func (mmLogIn *mUsersMockLogIn) ExpectUsernameParam1(username string) *mUsersMockLogIn {
	if mmLogIn.mock.funcLogIn != nil {
		mmLogIn.mock.t.Fatalf("UsersMock.LogIn mock is already set by Set")
	}

	if mmLogIn.defaultExpectation == nil {
		mmLogIn.defaultExpectation = &UsersMockLogInExpectation{}
	}

	if mmLogIn.defaultExpectation.params != nil {
		mmLogIn.mock.t.Fatalf("UsersMock.LogIn mock is already set by Expect")
	}

	if mmLogIn.defaultExpectation.paramPtrs == nil {
		mmLogIn.defaultExpectation.paramPtrs = &UsersMockLogInParamPtrs{}
	}
	mmLogIn.defaultExpectation.paramPtrs.username = &username
	mmLogIn.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmLogIn
}

// Inspect accepts an inspector function that has same arguments as the Users.LogIn
func (mmLogIn *mUsersMockLogIn) Inspect(f func(username string)) *mUsersMockLogIn {
	if mmLogIn.mock.inspectFuncLogIn != nil {
		mmLogIn.mock.t.Fatalf("Inspect function is already set for UsersMock.LogIn")
	}

	mmLogIn.mock.inspectFuncLogIn = f

	return mmLogIn
}

// Return sets up results that will be returned by Users.LogIn
func (mmLogIn *mUsersMockLogIn) Return(i1 int64, err error) *UsersMock {
	if mmLogIn.mock.funcLogIn != nil {
		mmLogIn.mock.t.Fatalf("UsersMock.LogIn mock is already set by Set")
	}

	if mmLogIn.defaultExpectation == nil {
		mmLogIn.defaultExpectation = &UsersMockLogInExpectation{mock: mmLogIn.mock}
	}
	mmLogIn.defaultExpectation.results = &UsersMockLogInResults{i1, err}
	mmLogIn.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLogIn.mock
}

// Set uses given function f to mock the Users.LogIn method
func (mmLogIn *mUsersMockLogIn) Set(f func(username string) (i1 int64, err error)) *UsersMock {
	if mmLogIn.defaultExpectation != nil {
		mmLogIn.mock.t.Fatalf("Default expectation is already set for the Users.LogIn method")
	}

	if len(mmLogIn.expectations) > 0 {
		mmLogIn.mock.t.Fatalf("Some expectations are already set for the Users.LogIn method")
	}

	mmLogIn.mock.funcLogIn = f
	mmLogIn.mock.funcLogInOrigin = minimock.CallerInfo(1)
	return mmLogIn.mock
}

// When sets expectation for the Users.LogIn which will trigger the result defined by the following
// Then helper
func (mmLogIn *mUsersMockLogIn) When(username string) *UsersMockLogInExpectation {
	if mmLogIn.mock.funcLogIn != nil {
		mmLogIn.mock.t.Fatalf("UsersMock.LogIn mock is already set by Set")
	}

	expectation := &UsersMockLogInExpectation{
		mock:               mmLogIn.mock,
		params:             &UsersMockLogInParams{username},
		expectationOrigins: UsersMockLogInExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLogIn.expectations = append(mmLogIn.expectations, expectation)
	return expectation
}

// Then sets up Users.LogIn return parameters for the expectation previously defined by the When method
func (e *UsersMockLogInExpectation) Then(i1 int64, err error) *UsersMock {
	e.results = &UsersMockLogInResults{i1, err}
	return e.mock
}

// Times sets number of times Users.LogIn should be invoked
func (mmLogIn *mUsersMockLogIn) Times(n uint64) *mUsersMockLogIn {
	if n == 0 {
		mmLogIn.mock.t.Fatalf("Times of UsersMock.LogIn mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLogIn.expectedInvocations, n)
	mmLogIn.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLogIn
}

func (mmLogIn *mUsersMockLogIn) invocationsDone() bool {
	if len(mmLogIn.expectations) == 0 && mmLogIn.defaultExpectation == nil && mmLogIn.mock.funcLogIn == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLogIn.mock.afterLogInCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLogIn.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// LogIn implements mm_repositories.Users
func (mmLogIn *UsersMock) LogIn(username string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmLogIn.beforeLogInCounter, 1)
	defer mm_atomic.AddUint64(&mmLogIn.afterLogInCounter, 1)

	mmLogIn.t.Helper()

	if mmLogIn.inspectFuncLogIn != nil {
		mmLogIn.inspectFuncLogIn(username)
	}

	mm_params := UsersMockLogInParams{username}

	// Record call args
	mmLogIn.LogInMock.mutex.Lock()
	mmLogIn.LogInMock.callArgs = append(mmLogIn.LogInMock.callArgs, &mm_params)
	mmLogIn.LogInMock.mutex.Unlock()

	for _, e := range mmLogIn.LogInMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmLogIn.LogInMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLogIn.LogInMock.defaultExpectation.Counter, 1)
		mm_want := mmLogIn.LogInMock.defaultExpectation.params
		mm_want_ptrs := mmLogIn.LogInMock.defaultExpectation.paramPtrs

		mm_got := UsersMockLogInParams{username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmLogIn.t.Errorf("UsersMock.LogIn got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogIn.LogInMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLogIn.t.Errorf("UsersMock.LogIn got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLogIn.LogInMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLogIn.LogInMock.defaultExpectation.results
		if mm_results == nil {
			mmLogIn.t.Fatal("No results are set for the UsersMock.LogIn")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmLogIn.funcLogIn != nil {
		return mmLogIn.funcLogIn(username)
	}
	mmLogIn.t.Fatalf("Unexpected call to UsersMock.LogIn. %v", username)
	return
}

// LogInAfterCounter returns a count of finished UsersMock.LogIn invocations
func (mmLogIn *UsersMock) LogInAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogIn.afterLogInCounter)
}

// LogInBeforeCounter returns a count of UsersMock.LogIn invocations
func (mmLogIn *UsersMock) LogInBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogIn.beforeLogInCounter)
}

// Calls returns a list of arguments used in each call to UsersMock.LogIn.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLogIn *mUsersMockLogIn) Calls() []*UsersMockLogInParams {
	mmLogIn.mutex.RLock()

	argCopy := make([]*UsersMockLogInParams, len(mmLogIn.callArgs))
	copy(argCopy, mmLogIn.callArgs)

	mmLogIn.mutex.RUnlock()

	return argCopy
}

// MinimockLogInDone returns true if the count of the LogIn invocations corresponds
// the number of defined expectations
func (m *UsersMock) MinimockLogInDone() bool {
	if m.LogInMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LogInMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LogInMock.invocationsDone()
}

// MinimockLogInInspect logs each unmet expectation
func (m *UsersMock) MinimockLogInInspect() {
	for _, e := range m.LogInMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersMock.LogIn at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLogInCounter := mm_atomic.LoadUint64(&m.afterLogInCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LogInMock.defaultExpectation != nil && afterLogInCounter < 1 {
		if m.LogInMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersMock.LogIn at\n%s", m.LogInMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersMock.LogIn at\n%s with params: %#v", m.LogInMock.defaultExpectation.expectationOrigins.origin, *m.LogInMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLogIn != nil && afterLogInCounter < 1 {
		m.t.Errorf("Expected call to UsersMock.LogIn at\n%s", m.funcLogInOrigin)
	}

	if !m.LogInMock.invocationsDone() && afterLogInCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersMock.LogIn at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LogInMock.expectedInvocations), m.LogInMock.expectedInvocationsOrigin, afterLogInCounter)
	}
}

type mUsersMockNewUser struct {
	optional           bool
	mock               *UsersMock
	defaultExpectation *UsersMockNewUserExpectation
	expectations       []*UsersMockNewUserExpectation

	callArgs []*UsersMockNewUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersMockNewUserExpectation specifies expectation struct of the Users.NewUser
type UsersMockNewUserExpectation struct {
	mock               *UsersMock
	params             *UsersMockNewUserParams
	paramPtrs          *UsersMockNewUserParamPtrs
	expectationOrigins UsersMockNewUserExpectationOrigins
	results            *UsersMockNewUserResults
	returnOrigin       string
	Counter            uint64
}

// UsersMockNewUserParams contains parameters of the Users.NewUser
type UsersMockNewUserParams struct {
	s1 string
}

// UsersMockNewUserParamPtrs contains pointers to parameters of the Users.NewUser
type UsersMockNewUserParamPtrs struct {
	s1 *string
}

// UsersMockNewUserResults contains results of the Users.NewUser
type UsersMockNewUserResults struct {
	i1  int64
	err error
}

// UsersMockNewUserOrigins contains origins of expectations of the Users.NewUser
type UsersMockNewUserExpectationOrigins struct {
	origin   string
	originS1 string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewUser *mUsersMockNewUser) Optional() *mUsersMockNewUser {
	mmNewUser.optional = true
	return mmNewUser
}

// Expect sets up expected params for Users.NewUser
func (mmNewUser *mUsersMockNewUser) Expect(s1 string) *mUsersMockNewUser {
	if mmNewUser.mock.funcNewUser != nil {
		mmNewUser.mock.t.Fatalf("UsersMock.NewUser mock is already set by Set")
	}

	if mmNewUser.defaultExpectation == nil {
		mmNewUser.defaultExpectation = &UsersMockNewUserExpectation{}
	}

	if mmNewUser.defaultExpectation.paramPtrs != nil {
		mmNewUser.mock.t.Fatalf("UsersMock.NewUser mock is already set by ExpectParams functions")
	}

	mmNewUser.defaultExpectation.params = &UsersMockNewUserParams{s1}
	mmNewUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmNewUser.expectations {
		if minimock.Equal(e.params, mmNewUser.defaultExpectation.params) {
			mmNewUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNewUser.defaultExpectation.params)
		}
	}

	return mmNewUser
}

// ExpectS1Param1 sets up expected param s1 for Users.NewUser
func (mmNewUser *mUsersMockNewUser) ExpectS1Param1(s1 string) *mUsersMockNewUser {
	if mmNewUser.mock.funcNewUser != nil {
		mmNewUser.mock.t.Fatalf("UsersMock.NewUser mock is already set by Set")
	}

	if mmNewUser.defaultExpectation == nil {
		mmNewUser.defaultExpectation = &UsersMockNewUserExpectation{}
	}

	if mmNewUser.defaultExpectation.params != nil {
		mmNewUser.mock.t.Fatalf("UsersMock.NewUser mock is already set by Expect")
	}

	if mmNewUser.defaultExpectation.paramPtrs == nil {
		mmNewUser.defaultExpectation.paramPtrs = &UsersMockNewUserParamPtrs{}
	}
	mmNewUser.defaultExpectation.paramPtrs.s1 = &s1
	mmNewUser.defaultExpectation.expectationOrigins.originS1 = minimock.CallerInfo(1)

	return mmNewUser
}

// Inspect accepts an inspector function that has same arguments as the Users.NewUser
func (mmNewUser *mUsersMockNewUser) Inspect(f func(s1 string)) *mUsersMockNewUser {
	if mmNewUser.mock.inspectFuncNewUser != nil {
		mmNewUser.mock.t.Fatalf("Inspect function is already set for UsersMock.NewUser")
	}

	mmNewUser.mock.inspectFuncNewUser = f

	return mmNewUser
}

// Return sets up results that will be returned by Users.NewUser
func (mmNewUser *mUsersMockNewUser) Return(i1 int64, err error) *UsersMock {
	if mmNewUser.mock.funcNewUser != nil {
		mmNewUser.mock.t.Fatalf("UsersMock.NewUser mock is already set by Set")
	}

	if mmNewUser.defaultExpectation == nil {
		mmNewUser.defaultExpectation = &UsersMockNewUserExpectation{mock: mmNewUser.mock}
	}
	mmNewUser.defaultExpectation.results = &UsersMockNewUserResults{i1, err}
	mmNewUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewUser.mock
}

// Set uses given function f to mock the Users.NewUser method
func (mmNewUser *mUsersMockNewUser) Set(f func(s1 string) (i1 int64, err error)) *UsersMock {
	if mmNewUser.defaultExpectation != nil {
		mmNewUser.mock.t.Fatalf("Default expectation is already set for the Users.NewUser method")
	}

	if len(mmNewUser.expectations) > 0 {
		mmNewUser.mock.t.Fatalf("Some expectations are already set for the Users.NewUser method")
	}

	mmNewUser.mock.funcNewUser = f
	mmNewUser.mock.funcNewUserOrigin = minimock.CallerInfo(1)
	return mmNewUser.mock
}

// When sets expectation for the Users.NewUser which will trigger the result defined by the following
// Then helper
func (mmNewUser *mUsersMockNewUser) When(s1 string) *UsersMockNewUserExpectation {
	if mmNewUser.mock.funcNewUser != nil {
		mmNewUser.mock.t.Fatalf("UsersMock.NewUser mock is already set by Set")
	}

	expectation := &UsersMockNewUserExpectation{
		mock:               mmNewUser.mock,
		params:             &UsersMockNewUserParams{s1},
		expectationOrigins: UsersMockNewUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmNewUser.expectations = append(mmNewUser.expectations, expectation)
	return expectation
}

// Then sets up Users.NewUser return parameters for the expectation previously defined by the When method
func (e *UsersMockNewUserExpectation) Then(i1 int64, err error) *UsersMock {
	e.results = &UsersMockNewUserResults{i1, err}
	return e.mock
}

// Times sets number of times Users.NewUser should be invoked
func (mmNewUser *mUsersMockNewUser) Times(n uint64) *mUsersMockNewUser {
	if n == 0 {
		mmNewUser.mock.t.Fatalf("Times of UsersMock.NewUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewUser.expectedInvocations, n)
	mmNewUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewUser
}

func (mmNewUser *mUsersMockNewUser) invocationsDone() bool {
	if len(mmNewUser.expectations) == 0 && mmNewUser.defaultExpectation == nil && mmNewUser.mock.funcNewUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewUser.mock.afterNewUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewUser implements mm_repositories.Users
func (mmNewUser *UsersMock) NewUser(s1 string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmNewUser.beforeNewUserCounter, 1)
	defer mm_atomic.AddUint64(&mmNewUser.afterNewUserCounter, 1)

	mmNewUser.t.Helper()

	if mmNewUser.inspectFuncNewUser != nil {
		mmNewUser.inspectFuncNewUser(s1)
	}

	mm_params := UsersMockNewUserParams{s1}

	// Record call args
	mmNewUser.NewUserMock.mutex.Lock()
	mmNewUser.NewUserMock.callArgs = append(mmNewUser.NewUserMock.callArgs, &mm_params)
	mmNewUser.NewUserMock.mutex.Unlock()

	for _, e := range mmNewUser.NewUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmNewUser.NewUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewUser.NewUserMock.defaultExpectation.Counter, 1)
		mm_want := mmNewUser.NewUserMock.defaultExpectation.params
		mm_want_ptrs := mmNewUser.NewUserMock.defaultExpectation.paramPtrs

		mm_got := UsersMockNewUserParams{s1}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.s1 != nil && !minimock.Equal(*mm_want_ptrs.s1, mm_got.s1) {
				mmNewUser.t.Errorf("UsersMock.NewUser got unexpected parameter s1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewUser.NewUserMock.defaultExpectation.expectationOrigins.originS1, *mm_want_ptrs.s1, mm_got.s1, minimock.Diff(*mm_want_ptrs.s1, mm_got.s1))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNewUser.t.Errorf("UsersMock.NewUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmNewUser.NewUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNewUser.NewUserMock.defaultExpectation.results
		if mm_results == nil {
			mmNewUser.t.Fatal("No results are set for the UsersMock.NewUser")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmNewUser.funcNewUser != nil {
		return mmNewUser.funcNewUser(s1)
	}
	mmNewUser.t.Fatalf("Unexpected call to UsersMock.NewUser. %v", s1)
	return
}

// NewUserAfterCounter returns a count of finished UsersMock.NewUser invocations
func (mmNewUser *UsersMock) NewUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewUser.afterNewUserCounter)
}

// NewUserBeforeCounter returns a count of UsersMock.NewUser invocations
func (mmNewUser *UsersMock) NewUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewUser.beforeNewUserCounter)
}

// Calls returns a list of arguments used in each call to UsersMock.NewUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNewUser *mUsersMockNewUser) Calls() []*UsersMockNewUserParams {
	mmNewUser.mutex.RLock()

	argCopy := make([]*UsersMockNewUserParams, len(mmNewUser.callArgs))
	copy(argCopy, mmNewUser.callArgs)

	mmNewUser.mutex.RUnlock()

	return argCopy
}

// MinimockNewUserDone returns true if the count of the NewUser invocations corresponds
// the number of defined expectations
func (m *UsersMock) MinimockNewUserDone() bool {
	if m.NewUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewUserMock.invocationsDone()
}

// MinimockNewUserInspect logs each unmet expectation
func (m *UsersMock) MinimockNewUserInspect() {
	for _, e := range m.NewUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersMock.NewUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterNewUserCounter := mm_atomic.LoadUint64(&m.afterNewUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewUserMock.defaultExpectation != nil && afterNewUserCounter < 1 {
		if m.NewUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersMock.NewUser at\n%s", m.NewUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersMock.NewUser at\n%s with params: %#v", m.NewUserMock.defaultExpectation.expectationOrigins.origin, *m.NewUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewUser != nil && afterNewUserCounter < 1 {
		m.t.Errorf("Expected call to UsersMock.NewUser at\n%s", m.funcNewUserOrigin)
	}

	if !m.NewUserMock.invocationsDone() && afterNewUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersMock.NewUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewUserMock.expectedInvocations), m.NewUserMock.expectedInvocationsOrigin, afterNewUserCounter)
	}
}

type mUsersMockUserExists struct {
	optional           bool
	mock               *UsersMock
	defaultExpectation *UsersMockUserExistsExpectation
	expectations       []*UsersMockUserExistsExpectation

	callArgs []*UsersMockUserExistsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UsersMockUserExistsExpectation specifies expectation struct of the Users.UserExists
type UsersMockUserExistsExpectation struct {
	mock               *UsersMock
	params             *UsersMockUserExistsParams
	paramPtrs          *UsersMockUserExistsParamPtrs
	expectationOrigins UsersMockUserExistsExpectationOrigins
	results            *UsersMockUserExistsResults
	returnOrigin       string
	Counter            uint64
}

// UsersMockUserExistsParams contains parameters of the Users.UserExists
type UsersMockUserExistsParams struct {
	username string
}

// UsersMockUserExistsParamPtrs contains pointers to parameters of the Users.UserExists
type UsersMockUserExistsParamPtrs struct {
	username *string
}

// UsersMockUserExistsResults contains results of the Users.UserExists
type UsersMockUserExistsResults struct {
	b1  bool
	err error
}

// UsersMockUserExistsOrigins contains origins of expectations of the Users.UserExists
type UsersMockUserExistsExpectationOrigins struct {
	origin         string
	originUsername string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUserExists *mUsersMockUserExists) Optional() *mUsersMockUserExists {
	mmUserExists.optional = true
	return mmUserExists
}

// Expect sets up expected params for Users.UserExists
func (mmUserExists *mUsersMockUserExists) Expect(username string) *mUsersMockUserExists {
	if mmUserExists.mock.funcUserExists != nil {
		mmUserExists.mock.t.Fatalf("UsersMock.UserExists mock is already set by Set")
	}

	if mmUserExists.defaultExpectation == nil {
		mmUserExists.defaultExpectation = &UsersMockUserExistsExpectation{}
	}

	if mmUserExists.defaultExpectation.paramPtrs != nil {
		mmUserExists.mock.t.Fatalf("UsersMock.UserExists mock is already set by ExpectParams functions")
	}

	mmUserExists.defaultExpectation.params = &UsersMockUserExistsParams{username}
	mmUserExists.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUserExists.expectations {
		if minimock.Equal(e.params, mmUserExists.defaultExpectation.params) {
			mmUserExists.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUserExists.defaultExpectation.params)
		}
	}

	return mmUserExists
}

// ExpectUsernameParam1 sets up expected param username for Users.UserExists
func (mmUserExists *mUsersMockUserExists) ExpectUsernameParam1(username string) *mUsersMockUserExists {
	if mmUserExists.mock.funcUserExists != nil {
		mmUserExists.mock.t.Fatalf("UsersMock.UserExists mock is already set by Set")
	}

	if mmUserExists.defaultExpectation == nil {
		mmUserExists.defaultExpectation = &UsersMockUserExistsExpectation{}
	}

	if mmUserExists.defaultExpectation.params != nil {
		mmUserExists.mock.t.Fatalf("UsersMock.UserExists mock is already set by Expect")
	}

	if mmUserExists.defaultExpectation.paramPtrs == nil {
		mmUserExists.defaultExpectation.paramPtrs = &UsersMockUserExistsParamPtrs{}
	}
	mmUserExists.defaultExpectation.paramPtrs.username = &username
	mmUserExists.defaultExpectation.expectationOrigins.originUsername = minimock.CallerInfo(1)

	return mmUserExists
}

// Inspect accepts an inspector function that has same arguments as the Users.UserExists
func (mmUserExists *mUsersMockUserExists) Inspect(f func(username string)) *mUsersMockUserExists {
	if mmUserExists.mock.inspectFuncUserExists != nil {
		mmUserExists.mock.t.Fatalf("Inspect function is already set for UsersMock.UserExists")
	}

	mmUserExists.mock.inspectFuncUserExists = f

	return mmUserExists
}

// Return sets up results that will be returned by Users.UserExists
func (mmUserExists *mUsersMockUserExists) Return(b1 bool, err error) *UsersMock {
	if mmUserExists.mock.funcUserExists != nil {
		mmUserExists.mock.t.Fatalf("UsersMock.UserExists mock is already set by Set")
	}

	if mmUserExists.defaultExpectation == nil {
		mmUserExists.defaultExpectation = &UsersMockUserExistsExpectation{mock: mmUserExists.mock}
	}
	mmUserExists.defaultExpectation.results = &UsersMockUserExistsResults{b1, err}
	mmUserExists.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUserExists.mock
}

// Set uses given function f to mock the Users.UserExists method
func (mmUserExists *mUsersMockUserExists) Set(f func(username string) (b1 bool, err error)) *UsersMock {
	if mmUserExists.defaultExpectation != nil {
		mmUserExists.mock.t.Fatalf("Default expectation is already set for the Users.UserExists method")
	}

	if len(mmUserExists.expectations) > 0 {
		mmUserExists.mock.t.Fatalf("Some expectations are already set for the Users.UserExists method")
	}

	mmUserExists.mock.funcUserExists = f
	mmUserExists.mock.funcUserExistsOrigin = minimock.CallerInfo(1)
	return mmUserExists.mock
}

// When sets expectation for the Users.UserExists which will trigger the result defined by the following
// Then helper
func (mmUserExists *mUsersMockUserExists) When(username string) *UsersMockUserExistsExpectation {
	if mmUserExists.mock.funcUserExists != nil {
		mmUserExists.mock.t.Fatalf("UsersMock.UserExists mock is already set by Set")
	}

	expectation := &UsersMockUserExistsExpectation{
		mock:               mmUserExists.mock,
		params:             &UsersMockUserExistsParams{username},
		expectationOrigins: UsersMockUserExistsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUserExists.expectations = append(mmUserExists.expectations, expectation)
	return expectation
}

// Then sets up Users.UserExists return parameters for the expectation previously defined by the When method
func (e *UsersMockUserExistsExpectation) Then(b1 bool, err error) *UsersMock {
	e.results = &UsersMockUserExistsResults{b1, err}
	return e.mock
}

// Times sets number of times Users.UserExists should be invoked
func (mmUserExists *mUsersMockUserExists) Times(n uint64) *mUsersMockUserExists {
	if n == 0 {
		mmUserExists.mock.t.Fatalf("Times of UsersMock.UserExists mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUserExists.expectedInvocations, n)
	mmUserExists.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUserExists
}

func (mmUserExists *mUsersMockUserExists) invocationsDone() bool {
	if len(mmUserExists.expectations) == 0 && mmUserExists.defaultExpectation == nil && mmUserExists.mock.funcUserExists == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUserExists.mock.afterUserExistsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUserExists.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UserExists implements mm_repositories.Users
func (mmUserExists *UsersMock) UserExists(username string) (b1 bool, err error) {
	mm_atomic.AddUint64(&mmUserExists.beforeUserExistsCounter, 1)
	defer mm_atomic.AddUint64(&mmUserExists.afterUserExistsCounter, 1)

	mmUserExists.t.Helper()

	if mmUserExists.inspectFuncUserExists != nil {
		mmUserExists.inspectFuncUserExists(username)
	}

	mm_params := UsersMockUserExistsParams{username}

	// Record call args
	mmUserExists.UserExistsMock.mutex.Lock()
	mmUserExists.UserExistsMock.callArgs = append(mmUserExists.UserExistsMock.callArgs, &mm_params)
	mmUserExists.UserExistsMock.mutex.Unlock()

	for _, e := range mmUserExists.UserExistsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.b1, e.results.err
		}
	}

	if mmUserExists.UserExistsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUserExists.UserExistsMock.defaultExpectation.Counter, 1)
		mm_want := mmUserExists.UserExistsMock.defaultExpectation.params
		mm_want_ptrs := mmUserExists.UserExistsMock.defaultExpectation.paramPtrs

		mm_got := UsersMockUserExistsParams{username}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.username != nil && !minimock.Equal(*mm_want_ptrs.username, mm_got.username) {
				mmUserExists.t.Errorf("UsersMock.UserExists got unexpected parameter username, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUserExists.UserExistsMock.defaultExpectation.expectationOrigins.originUsername, *mm_want_ptrs.username, mm_got.username, minimock.Diff(*mm_want_ptrs.username, mm_got.username))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUserExists.t.Errorf("UsersMock.UserExists got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUserExists.UserExistsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUserExists.UserExistsMock.defaultExpectation.results
		if mm_results == nil {
			mmUserExists.t.Fatal("No results are set for the UsersMock.UserExists")
		}
		return (*mm_results).b1, (*mm_results).err
	}
	if mmUserExists.funcUserExists != nil {
		return mmUserExists.funcUserExists(username)
	}
	mmUserExists.t.Fatalf("Unexpected call to UsersMock.UserExists. %v", username)
	return
}

// UserExistsAfterCounter returns a count of finished UsersMock.UserExists invocations
func (mmUserExists *UsersMock) UserExistsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserExists.afterUserExistsCounter)
}

// UserExistsBeforeCounter returns a count of UsersMock.UserExists invocations
func (mmUserExists *UsersMock) UserExistsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUserExists.beforeUserExistsCounter)
}

// Calls returns a list of arguments used in each call to UsersMock.UserExists.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUserExists *mUsersMockUserExists) Calls() []*UsersMockUserExistsParams {
	mmUserExists.mutex.RLock()

	argCopy := make([]*UsersMockUserExistsParams, len(mmUserExists.callArgs))
	copy(argCopy, mmUserExists.callArgs)

	mmUserExists.mutex.RUnlock()

	return argCopy
}

// MinimockUserExistsDone returns true if the count of the UserExists invocations corresponds
// the number of defined expectations
func (m *UsersMock) MinimockUserExistsDone() bool {
	if m.UserExistsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UserExistsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UserExistsMock.invocationsDone()
}

// MinimockUserExistsInspect logs each unmet expectation
func (m *UsersMock) MinimockUserExistsInspect() {
	for _, e := range m.UserExistsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UsersMock.UserExists at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUserExistsCounter := mm_atomic.LoadUint64(&m.afterUserExistsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UserExistsMock.defaultExpectation != nil && afterUserExistsCounter < 1 {
		if m.UserExistsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UsersMock.UserExists at\n%s", m.UserExistsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UsersMock.UserExists at\n%s with params: %#v", m.UserExistsMock.defaultExpectation.expectationOrigins.origin, *m.UserExistsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUserExists != nil && afterUserExistsCounter < 1 {
		m.t.Errorf("Expected call to UsersMock.UserExists at\n%s", m.funcUserExistsOrigin)
	}

	if !m.UserExistsMock.invocationsDone() && afterUserExistsCounter > 0 {
		m.t.Errorf("Expected %d calls to UsersMock.UserExists at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UserExistsMock.expectedInvocations), m.UserExistsMock.expectedInvocationsOrigin, afterUserExistsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UsersMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLogInInspect()

			m.MinimockNewUserInspect()

			m.MinimockUserExistsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UsersMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UsersMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLogInDone() &&
		m.MinimockNewUserDone() &&
		m.MinimockUserExistsDone()
}
